version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile #Dockerfile.dev
        ports:
            - '8181:3000'
        volumes:
            - /app/node_modules
            - .:/app
    teste:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ['npm', 'run', 'test']
